# Shared Xomware Cognito User Pool
# -------------------------------------------------------------------
# This pool is the org-level identity provider for all Xomware apps
# (xomware.com, xomappetit, future apps). Per-app App Clients live
# below; consumer apps read pool ARN/IDs via SSM exports (see
# cognito_ssm.tf).
#
# Option B applied: alias_attributes only. The underlying Cognito
# Username is an opaque UUID generated by Amplify at signup. Users
# sign in with email or @handle (preferred_username), both enforced
# unique by Cognito.
#
# WARNING: schema_attributes, password_policy, alias_attributes, and
# username_attributes are ALL replacement-forced. Changing any of
# these destroys the pool and every user. Review carefully.
# -------------------------------------------------------------------

resource "aws_cognito_user_pool" "xomware_users" {
  name = "xomware-users"

  # Opaque UUID Username supplied at signup; sign-in via email alias only.
  # preferred_username is INTENTIONALLY NOT an alias attribute and NOT in
  # the required schema below — Cognito refuses to set alias attrs at
  # SignUp time (reserved for confirmed accounts) AND requires any
  # required-schema attr at SignUp. The combination is a catch-22.
  # Solution: handles live exclusively in DynamoDB
  # (xomware-users.preferredUsername). Uniqueness enforced by app logic
  # via the handle-index GSI.
  alias_attributes         = ["email"]
  auto_verified_attributes = ["email"]

  # INACTIVE during the catch-22 fix sequence. Will be re-enabled in a
  # follow-up PR once the new pool is verified working with signup.
  deletion_protection = "INACTIVE"

  user_pool_tier = "ESSENTIALS"

  password_policy {
    minimum_length                   = 8
    require_uppercase                = true
    require_lowercase                = true
    require_numbers                  = true
    require_symbols                  = false
    temporary_password_validity_days = 7
  }

  # MFA off for v1.
  mfa_configuration = "OFF"

  account_recovery_setting {
    recovery_mechanism {
      name     = "verified_email"
      priority = 1
    }
  }

  admin_create_user_config {
    allow_admin_create_user_only = false
  }

  # Email — Cognito default sender. SES customization deferred to Phase 6.
  email_configuration {
    email_sending_account = "COGNITO_DEFAULT"
  }

  # Branded verification email. Default Cognito sender (SES customization
  # is a follow-up — to put noreply@xomware.com on the From line we need
  # to verify the xomware.com domain in SES first). HTML body only; the
  # recipient's client falls back to the {####} code in plaintext if HTML
  # doesn't render.
  verification_message_template {
    default_email_option = "CONFIRM_WITH_CODE"
    email_subject        = "Verify your Xomware account"
    email_message        = <<-HTML
      <!DOCTYPE html>
      <html>
      <body style="margin:0;padding:0;background:#0a0a0b;font-family:-apple-system,system-ui,sans-serif;">
        <table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 20px;background:#0a0a0b;">
          <tr><td align="center">
            <table width="480" cellpadding="0" cellspacing="0" style="background:#18181b;border:1px solid #27272a;border-radius:12px;padding:32px;text-align:left;">
              <tr><td>
                <div style="font-size:24px;font-weight:900;letter-spacing:-0.02em;color:#00b4d8;">XOMWARE</div>
                <div style="height:3px;width:48px;background:linear-gradient(90deg,#00b4d8,#48cae4);border-radius:2px;margin:8px 0 24px 0;"></div>
                <h2 style="margin:0 0 12px 0;color:#fafafa;font-size:20px;font-weight:700;">Verify your email</h2>
                <p style="margin:0 0 20px 0;color:#a1a1aa;font-size:15px;line-height:1.5;">Welcome. Use the code below to finish creating your Xomware account:</p>
                <div style="background:#0a0a0b;border:1px solid #00b4d833;border-radius:8px;padding:20px;text-align:center;font-size:32px;letter-spacing:0.3em;color:#00b4d8;font-weight:700;font-family:ui-monospace,monospace;">{####}</div>
                <p style="margin:24px 0 0 0;color:#52525b;font-size:13px;line-height:1.5;">Code expires in 24 hours. If you didn't sign up, ignore this email.</p>
              </td></tr>
            </table>
            <p style="margin:24px 0 0 0;color:#52525b;font-size:11px;text-align:center;">Xomware &middot; xomware.com</p>
          </td></tr>
        </table>
      </body>
      </html>
    HTML
  }

  # Required schema attributes. Only email is enforced at the Cognito layer.
  # Handle (preferredUsername) lives in DynamoDB — see comment on alias_attributes.
  schema {
    name                     = "email"
    attribute_data_type      = "String"
    required                 = true
    mutable                  = true
    developer_only_attribute = false

    string_attribute_constraints {
      min_length = 1
      max_length = 256
    }
  }

  # Self-service signup is implicitly enabled (allow_admin_create_user_only = false).
  # No custom attributes — profile data lives in DynamoDB (Phase 3).

  # Phase 3: PostConfirmation Lambda trigger writes the user row to
  # xomware-users on email-verified signup. Per AWS provider docs this is an
  # in-place update (NOT replacement). See lambdas_users.tf for the Lambda.
  #
  # Phase 4: PreSignUp Lambda trigger auto-links federated (Google) identities
  # to existing native Cognito users when emails match — prevents duplicate
  # accounts on first Google sign-in for an existing user.
  #
  # Phase 5: PostAuthentication trigger writes a `signin` event to
  # xomware-events for the /admin portal audit log.
  lambda_config {
    post_confirmation   = aws_lambda_function.users["create"].arn
    pre_sign_up         = aws_lambda_function.users["presignup_link"].arn
    post_authentication = aws_lambda_function.auth_track.arn
  }

  tags = merge(local.standard_tags, {
    "environment" = "shared"
    "owner"       = "xomware"
    "purpose"     = "shared-identity"
  })

  lifecycle {
    ignore_changes = [tags_all]
  }
}

# Allow Cognito to invoke the users-create PostConfirmation lambda.
resource "aws_lambda_permission" "users_create_cognito" {
  statement_id  = "AllowCognitoInvokeUsersCreate"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.users["create"].function_name
  principal     = "cognito-idp.amazonaws.com"
  source_arn    = aws_cognito_user_pool.xomware_users.arn
}

# Allow Cognito to invoke the users-presignup-link PreSignUp lambda.
resource "aws_lambda_permission" "users_presignup_link_cognito" {
  statement_id  = "AllowCognitoInvokeUsersPreSignupLink"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.users["presignup_link"].function_name
  principal     = "cognito-idp.amazonaws.com"
  source_arn    = aws_cognito_user_pool.xomware_users.arn
}

# Allow Cognito to invoke the auth-track PostAuthentication lambda.
resource "aws_lambda_permission" "auth_track_cognito" {
  statement_id  = "AllowCognitoInvokeAuthTrack"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.auth_track.function_name
  principal     = "cognito-idp.amazonaws.com"
  source_arn    = aws_cognito_user_pool.xomware_users.arn
}

# Hosted UI domain (Amazon-hosted prefix).
# Custom domain (auth.xomware.com) deferred to Phase 6.
resource "aws_cognito_user_pool_domain" "xomware_auth" {
  domain       = "xomware-auth"
  user_pool_id = aws_cognito_user_pool.xomware_users.id
}

# -------------------------------------------------------------------
# App Clients — one per consumer app.
# -------------------------------------------------------------------

resource "aws_cognito_user_pool_client" "xomware_com" {
  name         = "xomware-com-client"
  user_pool_id = aws_cognito_user_pool.xomware_users.id

  generate_secret = false

  explicit_auth_flows = [
    "ALLOW_USER_SRP_AUTH",
    "ALLOW_REFRESH_TOKEN_AUTH",
  ]

  allowed_oauth_flows                  = ["code"]
  allowed_oauth_flows_user_pool_client = true
  allowed_oauth_scopes                 = ["email", "openid", "profile"]

  callback_urls = [
    "https://xomware.com/auth/callback",
    "http://localhost:4200/auth/callback",
  ]

  logout_urls = [
    "https://xomware.com",
    "http://localhost:4200",
  ]

  # Google added in Phase 4. The Google IdP must exist before this client
  # can list it; explicit depends_on guarantees ordering.
  supported_identity_providers = ["COGNITO", "Google"]

  depends_on = [aws_cognito_identity_provider.google]

  prevent_user_existence_errors = "ENABLED"
  enable_token_revocation       = true

  id_token_validity      = 60
  access_token_validity  = 60
  refresh_token_validity = 30

  token_validity_units {
    id_token      = "minutes"
    access_token  = "minutes"
    refresh_token = "days"
  }
}

resource "aws_cognito_user_pool_client" "xomappetit" {
  name         = "xomappetit-client"
  user_pool_id = aws_cognito_user_pool.xomware_users.id

  generate_secret = false

  explicit_auth_flows = [
    "ALLOW_USER_SRP_AUTH",
    "ALLOW_REFRESH_TOKEN_AUTH",
  ]

  allowed_oauth_flows                  = ["code"]
  allowed_oauth_flows_user_pool_client = true
  allowed_oauth_scopes                 = ["email", "openid", "profile"]

  callback_urls = [
    "https://xn--xomapptit-g4a.xomware.com/auth/callback",
    "https://xomappetit.xomware.com/auth/callback",
    "http://localhost:3000/auth/callback",
  ]

  logout_urls = [
    "https://xn--xomapptit-g4a.xomware.com",
    "https://xomappetit.xomware.com",
    "http://localhost:3000",
  ]

  # Google added in Phase 4. See xomware_com client comment.
  supported_identity_providers = ["COGNITO", "Google"]

  depends_on = [aws_cognito_identity_provider.google]

  prevent_user_existence_errors = "ENABLED"
  enable_token_revocation       = true

  id_token_validity      = 60
  access_token_validity  = 60
  refresh_token_validity = 30

  token_validity_units {
    id_token      = "minutes"
    access_token  = "minutes"
    refresh_token = "days"
  }
}

# -------------------------------------------------------------------
# Admin group — JWT claim `cognito:groups` flows into APIs and gates
# the /admin portal route in xomware-frontend.
# -------------------------------------------------------------------

resource "aws_cognito_user_group" "admin" {
  name         = "admin"
  user_pool_id = aws_cognito_user_pool.xomware_users.id
  description  = "Xomware admin group — full access to /admin portal"
  precedence   = 1
}

# Admin membership — lift each Cognito sub from `var.admin_user_subs` into
# the admin group. Default list is empty; populate via terraform.tfvars
# AFTER your first signup (find your sub on the /profile page or by
# decoding your JWT). Re-apply to grant.
variable "admin_user_subs" {
  description = "Cognito subs (UUIDs) to put in the admin group"
  type        = list(string)
  default     = []
}

resource "aws_cognito_user_in_group" "admins" {
  for_each     = toset(var.admin_user_subs)
  user_pool_id = aws_cognito_user_pool.xomware_users.id
  group_name   = aws_cognito_user_group.admin.name
  username     = each.value
}
