# Shared Xomware Cognito User Pool
# -------------------------------------------------------------------
# This pool is the org-level identity provider for all Xomware apps
# (xomware.com, xomappetit, future apps). Per-app App Clients live
# below; consumer apps read pool ARN/IDs via SSM exports (see
# cognito_ssm.tf).
#
# Option B applied: alias_attributes only. The underlying Cognito
# Username is an opaque UUID generated by Amplify at signup. Users
# sign in with email or @handle (preferred_username), both enforced
# unique by Cognito.
#
# WARNING: schema_attributes, password_policy, alias_attributes, and
# username_attributes are ALL replacement-forced. Changing any of
# these destroys the pool and every user. Review carefully.
# -------------------------------------------------------------------

resource "aws_cognito_user_pool" "xomware_users" {
  name = "xomware-users"

  # Opaque UUID Username supplied at signup; sign-in via aliases.
  alias_attributes         = ["email", "preferred_username"]
  auto_verified_attributes = ["email"]

  deletion_protection = "ACTIVE"

  user_pool_tier = "ESSENTIALS"

  password_policy {
    minimum_length                   = 8
    require_uppercase                = true
    require_lowercase                = true
    require_numbers                  = true
    require_symbols                  = false
    temporary_password_validity_days = 7
  }

  # MFA off for v1.
  mfa_configuration = "OFF"

  account_recovery_setting {
    recovery_mechanism {
      name     = "verified_email"
      priority = 1
    }
  }

  admin_create_user_config {
    allow_admin_create_user_only = false
  }

  # Email — Cognito default sender. SES customization deferred to Phase 6.
  email_configuration {
    email_sending_account = "COGNITO_DEFAULT"
  }

  # Required schema attributes. Both required + mutable.
  # preferred_username uniqueness is enforced via alias_attributes above.
  schema {
    name                     = "email"
    attribute_data_type      = "String"
    required                 = true
    mutable                  = true
    developer_only_attribute = false

    string_attribute_constraints {
      min_length = 1
      max_length = 256
    }
  }

  schema {
    name                     = "preferred_username"
    attribute_data_type      = "String"
    required                 = true
    mutable                  = true
    developer_only_attribute = false

    string_attribute_constraints {
      min_length = 3
      max_length = 20
    }
  }

  # Self-service signup is implicitly enabled (allow_admin_create_user_only = false).
  # No custom attributes — profile data lives in DynamoDB (Phase 3).

  # Phase 3: PostConfirmation Lambda trigger writes the user row to
  # xomware-users on email-verified signup. Per AWS provider docs this is an
  # in-place update (NOT replacement). See lambdas_users.tf for the Lambda.
  lambda_config {
    post_confirmation = aws_lambda_function.users["create"].arn
  }

  tags = merge(local.standard_tags, {
    "environment" = "shared"
    "owner"       = "xomware"
    "purpose"     = "shared-identity"
  })

  lifecycle {
    ignore_changes = [tags_all]
  }
}

# Allow Cognito to invoke the users-create PostConfirmation lambda.
resource "aws_lambda_permission" "users_create_cognito" {
  statement_id  = "AllowCognitoInvokeUsersCreate"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.users["create"].function_name
  principal     = "cognito-idp.amazonaws.com"
  source_arn    = aws_cognito_user_pool.xomware_users.arn
}

# Hosted UI domain (Amazon-hosted prefix).
# Custom domain (auth.xomware.com) deferred to Phase 6.
resource "aws_cognito_user_pool_domain" "xomware_auth" {
  domain       = "xomware-auth"
  user_pool_id = aws_cognito_user_pool.xomware_users.id
}

# -------------------------------------------------------------------
# App Clients — one per consumer app.
# -------------------------------------------------------------------

resource "aws_cognito_user_pool_client" "xomware_com" {
  name         = "xomware-com-client"
  user_pool_id = aws_cognito_user_pool.xomware_users.id

  generate_secret = false

  explicit_auth_flows = [
    "ALLOW_USER_SRP_AUTH",
    "ALLOW_REFRESH_TOKEN_AUTH",
  ]

  allowed_oauth_flows                  = ["code"]
  allowed_oauth_flows_user_pool_client = true
  allowed_oauth_scopes                 = ["email", "openid", "profile"]

  callback_urls = [
    "https://xomware.com/auth/callback",
    "http://localhost:4200/auth/callback",
  ]

  logout_urls = [
    "https://xomware.com",
    "http://localhost:4200",
  ]

  supported_identity_providers = ["COGNITO"]

  prevent_user_existence_errors = "ENABLED"
  enable_token_revocation       = true

  id_token_validity      = 60
  access_token_validity  = 60
  refresh_token_validity = 30

  token_validity_units {
    id_token      = "minutes"
    access_token  = "minutes"
    refresh_token = "days"
  }
}

resource "aws_cognito_user_pool_client" "xomappetit" {
  name         = "xomappetit-client"
  user_pool_id = aws_cognito_user_pool.xomware_users.id

  generate_secret = false

  explicit_auth_flows = [
    "ALLOW_USER_SRP_AUTH",
    "ALLOW_REFRESH_TOKEN_AUTH",
  ]

  allowed_oauth_flows                  = ["code"]
  allowed_oauth_flows_user_pool_client = true
  allowed_oauth_scopes                 = ["email", "openid", "profile"]

  callback_urls = [
    "https://xn--xomapptit-g4a.xomware.com/auth/callback",
    "https://xomappetit.xomware.com/auth/callback",
    "http://localhost:3000/auth/callback",
  ]

  logout_urls = [
    "https://xn--xomapptit-g4a.xomware.com",
    "https://xomappetit.xomware.com",
    "http://localhost:3000",
  ]

  supported_identity_providers = ["COGNITO"]

  prevent_user_existence_errors = "ENABLED"
  enable_token_revocation       = true

  id_token_validity      = 60
  access_token_validity  = 60
  refresh_token_validity = 30

  token_validity_units {
    id_token      = "minutes"
    access_token  = "minutes"
    refresh_token = "days"
  }
}

# -------------------------------------------------------------------
# Admin group — JWT claim `cognito:groups` flows into APIs and gates
# the /admin portal route in xomware-frontend.
# -------------------------------------------------------------------

resource "aws_cognito_user_group" "admin" {
  name         = "admin"
  user_pool_id = aws_cognito_user_pool.xomware_users.id
  description  = "Xomware admin group — full access to /admin portal"
  precedence   = 1
}
